### ISSUE TITLE
The 1.7.10 version crashes while making a world

### ISSUE THREAD

**Issue by crunkazcanbe** [Ri5ux/EnjinPlugin-MinecraftForge#2]
As the title says . It is taking forever to make a world and gets to about 25% and crashes .
http://pastebin.com/ZZcD75j9

Thank you 

-Crunk

**Comment by hsyyid** [comment]
That log doesn't say it's caused by Enjin. In fact you have lots of mods

**Comment by crunkazcanbe** [comment]
OK I uninstalled every mod ,and still right after the world was made I got a crash http://pastebin.com/TaGWAJMi

**Comment by hsyyid** [comment]
Enjin literally does not touch the world. It is a SERVER-SIDE mod though. So if you're running a client with it, then it will crash.

**Comment by Ri5ux** [comment]
You do NOT install the Enjin Plugin on the client.

**Comment by crunkazcanbe** [comment]
Testing a mod pack out I am creating .
