### ISSUE TITLE
Server crash after i enter the auth key

### ISSUE THREAD

**Issue by shone-zmaj** [Ri5ux/EnjinPlugin-MinecraftForge#3]
My server constantly crashes when i enter the authkey, but works fine when i remove it

heres the link for crash log
http://pastebin.com/xjhtg5DV

**Comment by Ri5ux** [comment]
Try Java 8 and let me know what the result is. I believe there may be some code that was done using a Java 8 specific feature.

**Comment by shone-zmaj** [comment]
Switching to java 8 works it didn't crash and everything else works fine so far, i didn't notice the server was running on java 7 sorry
