### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Noobsloth** [Ri5ux/EnjinPlugin-MinecraftForge#4]
No new push for 4 months so I was wanting to make sure if this project still works properly with enjin....

And also where I can grab a compiled download at since I dont trust myself to compile it correctly.

**Comment by hsyyid** [comment]
It works fine, you can grab a download here: http://www.curse.com/mc-mods/minecraft/234897-enjinforgeplugin

**Comment by Noobsloth** [comment]
Tyvm@ :D
