### ISSUE TITLE
Conflict

### ISSUE THREAD

**Issue by Favorlock** [Ri5ux/EnjinPlugin-MinecraftForge#6]
Hello, I am Favorlock, the current developer at Enjin. Please make this repo private or remove it completely. Our source code is private at this time and ripping the source and releasing a modified version without consent goes against community ethics.

Thanks for understanding.

Regards,
Favorlock

**Comment by Ri5ux** [comment]
Then perhaps you'd like to fix your plugin, instead of leaving it to rot.

**Comment by Favorlock** [comment]
Or, we can just submit a DMCA since you're not cooperating. Do we really need to go to such lengths?

**Comment by devanchya** [comment]
Bukkit is dead.   Gone, Boom.  Caboom.

Why are "professionals" not upgrading their forge code to be properly compatible.    You leave the community scrambling and this is the result.   I do not support use of code that is not properly open source.   I however understand the issues the community feels as Enjin, Buycraft, and other companies which make money off the community refuse to support a modern community.

**Comment by Favorlock** [comment]
You're incorrect about Bukkit being dead devanchya, what do you think Spigot is? It's bukkit, and it continues to be updated and used by thousands upon thousands of servers. Most of Enjin's client base is for Bukkit.

I can't speak for the previous developers of the Enjin plugin, but I can say that we are working towards updating our support for forge, but it takes time, especially considering that we maintain codebases for 4 different platforms.

I do agree that it would be best if the Enjin Minecraft Plugin was open source, but that is not my decision and I have already discussed it with my superiors, and at this time they do not feel that it would benefit Enjin to go open source with our plugins. I however do not agree with developers stealing intellectual property and releasing it to the public. Because the source code uploaded to this repo is a derivative and rip of the 2.x source code we cannot simply let things be. I have kindly asked that the repo be made private or removed.

A DMCA will likely be submitted by my superiors soon. Please make the smart decision and comply with our request.

**Comment by hsyyid** [comment]
@Favorlock So your only problem is with the source being public, nothing else? If so, I'll make the repo private but the downloads of this will stay up until your Forge version is finished.

Does that "comply with your request"?

**Comment by Ri5ux** [comment]
Feel free to submit yourself a DMCA. I have no reason to cooperate with you.
